name: Create Lineage 20 TD Images

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Cleanup
      uses: ./.github/actions/cleanup-runner
    
    - name: Run prerequisites
      uses: ./.github/actions/create-lineage-builder

    - name: Show available size
      run: df -h

    - name: Execute Action
      run: |
        cd $CheckoutDir/android/lineage
        git clone https://github.com/lesching-git/lineage_build_unified lineage_build_unified -b lineage-20-light
        # git clone https://github.com/AndyCGYan/lineage_patches_unified lineage_patches_unified -b lineage-20-light
        bash lineage_build_unified/buildbot_unified.sh treble 64VN

    - name: Download of build-output
      uses: actions/download-artifact@v4
      with:
          name: build-output
          path: /root/build-output
